version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/BookInventory
hooks:
 BeforeInstall:
   - location: scripts/before_script.sh
     runas: root

ApplicationStart:
    - location: scripts/application_start.sh
      runas: root
