version: 2.0
os: linux
files:
   - source: /server.js
     destination: /home/ubuntu/BookInventoryManagementSystem
hooks:
 BeforeInstall:
   - location: scripts/before_script.sh
     runas: root

ApplicationStart:
    - location: scripts/application_start.sh
      runas: root
