version: 2.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/BookInventoryManagementSystem
hooks:
 BeforeInstall:
   - location: scripts/before_script.sh
     runas: root
 
 AfterInstall:
   - location: scripts/after_script.sh
     runas: root

ApplicationStart:
    - location: scripts/applicationStart.sh
      runas: root
